### ISSUE TITLE
Running 'setup.py' hashview tries to connect to MySQL using mysql-password@localhost (Ubuntu 22.04 on WSL2 | Windows 11)

### ISSUE THREAD

**Issue by InfiniteBSOD** [hashview/hashview#106]
OS: Ubuntu 22.04.2 LTS running on WSL2

Hello,

Just tried setting up Hashview on my Ubuntu 22.04.2 (WSL2 running on Windows 11).

I created the "hashview" database as well as the "hashview" MySQL-user:
```
mysql> SHOW DATABASES;
+--------------------+
| Database           |
+--------------------+
| hashview           |
| information_schema |
| mysql              |
| performance_schema |
| sys                |
+--------------------+
5 rows in set (0.01 sec)

mysql> SELECT user FROM mysql.user;
+------------------+
| user             |
+------------------+
| debian-sys-maint |
| hashview         |
| mysql.infoschema |
| mysql.session    |
| mysql.sys        |
| root             |
+------------------+
6 rows in set (0.00 sec)
```

When running `./setup.py` to setup hashview and selecting a clean install I enter:
```
Enter the IP or hostname of the server running mysql. i.e. 127.0.0.1 or localhost: localhost
Enter the user account hashview should use to connect to the mysql instance: hashview
Enter the password for hashview: <my-mysql-password-for-the-mysql-user-hashview>
<omitting some stuff>
_mysql_connector.MySQLInterfaceError: Unknown MySQL server host '<my-mysql-password-for-the-mysql-user-hashview>@localhost' (-2)
sqlalchemy.exc.DatabaseError: (mysql.connector.errors.DatabaseError) 2005 (HY000): Unknown MySQL server host '<my-mysql-password-for-the-mysql-user-hashview>@localhost'
```

Err... shouldn't it try to connect to MySQL using `hashview@localhost` and the provided password instead of `<my-mysql-password-for-the-mysql-user-hashview>@localhost`?

Sorry if I missed something obvious, a bit new to Linux.

Best Regards

**Comment by i128** [comment]
Am i correct in understanding that the password you used for the mysql user is showing up in your error?

_mysql_connector.MySQLInterfaceError: Unknown MySQL server host '<my-mysql-password-for-the-mysql-user-hashview>@localhost' (-2)
sqlalchemy.exc.DatabaseError: (mysql.connector.errors.DatabaseError) 2005 (HY000): Unknown MySQL server host '<my-mysql-password-for-the-mysql-user-hashview>@localhost'

**Comment by InfiniteBSOD** [comment]
@i128 

Thank you for your quick reply, yes that is correct.
The password is shown preceeding "@localhost" in the error messages above

**Comment by i128** [comment]
After you run setup.py it should create a file at `./hashview/config.conf`. Check that file to see if the username/password for the mysql hashview account is correct. If its wrong, you can modify the file manually.

**Comment by InfiniteBSOD** [comment]
@i128 

Thank you, I checked the file and the user / pass for the MySQL-user for hashview are correct.

However when trying to start hashview with "./hashview.py":
```
ubuntu@wsl2:~/git/hashview$ ./hashview.py
Exception!:
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/mysql/connector/connection_cext.py", line 288, in _open_connection
    self._cmysql.connect(**cnx_kwargs)
_mysql_connector.MySQLInterfaceError: Unknown MySQL server host '<my-mysql-password-for-the-mysql-user-hashview>@localhost' (-2)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 145, in __init__
    self._dbapi_connection = engine.raw_connection()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3275, in raw_connection
    return self.pool.connect()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 455, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 1271, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 719, in checkout
    rec = pool._do_get()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 283, in _do_get
    return self._create_connection()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 396, in _create_connection
    return _ConnectionRecord(self)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 681, in __init__
    self.__connect()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 905, in __connect
    with util.safe_reraise():
  File "/home/ubuntu/.local/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 147, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 901, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 640, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 580, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/mysql/connector/pooling.py", line 293, in connect
    return CMySQLConnection(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/mysql/connector/connection_cext.py", line 118, in __init__
    self.connect(**kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/mysql/connector/abstracts.py", line 1178, in connect
    self._open_connection()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/mysql/connector/connection_cext.py", line 293, in _open_connection
    raise get_mysql_exception(
mysql.connector.errors.DatabaseError: 2005 (HY000): Unknown MySQL server host '<my-mysql-password-for-the-mysql-user-hashview>@localhost' (-2)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/git/hashview/./hashview.py", line 343, in cli
    ensure_version_alignment()
  File "/home/ubuntu/git/hashview/./hashview.py", line 232, in ensure_version_alignment
    upgrade()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask_migrate/__init__.py", line 111, in wrapped
    f(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask_migrate/__init__.py", line 200, in upgrade
    command.upgrade(config, revision, sql=sql, tag=tag)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/alembic/command.py", line 378, in upgrade
    script.run_env()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/alembic/script/base.py", line 576, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/home/ubuntu/.local/lib/python3.10/site-packages/alembic/util/pyfiles.py", line 94, in load_python_file
    module = load_module_py(module_id, path)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/alembic/util/pyfiles.py", line 110, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ubuntu/git/hashview/migrations/env.py", line 96, in <module>
    run_migrations_online()
  File "/home/ubuntu/git/hashview/migrations/env.py", line 81, in run_migrations_online
    with connectable.connect() as connection:
  File "/home/ubuntu/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3251, in connect
    return self._connection_cls(self)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 147, in __init__
    Connection._handle_dbapi_exception_noconnection(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2413, in _handle_dbapi_exception_noconnection
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/ubuntu/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 145, in __init__
    self._dbapi_connection = engine.raw_connection()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3275, in raw_connection
    return self.pool.connect()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 455, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 1271, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 719, in checkout
    rec = pool._do_get()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 283, in _do_get
    return self._create_connection()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 396, in _create_connection
    return _ConnectionRecord(self)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 681, in __init__
    self.__connect()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 905, in __connect
    with util.safe_reraise():
  File "/home/ubuntu/.local/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 147, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 901, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 640, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 580, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/mysql/connector/pooling.py", line 293, in connect
    return CMySQLConnection(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/mysql/connector/connection_cext.py", line 118, in __init__
    self.connect(**kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/mysql/connector/abstracts.py", line 1178, in connect
    self._open_connection()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/mysql/connector/connection_cext.py", line 293, in _open_connection
    raise get_mysql_exception(
sqlalchemy.exc.DatabaseError: (mysql.connector.errors.DatabaseError) 2005 (HY000): Unknown MySQL server host '<my-mysql-password-for-the-mysql-user-hashview>@localhost' (-2)
(Background on this error at: https://sqlalche.me/e/20/4xp6)
```

**Comment by i128** [comment]
Can you post the config here (with the password omitted)
Does your password contain any special characters, `;` or `=` for example?

**Comment by InfiniteBSOD** [comment]
> Can you post the config here (with the password omitted) Does your password contain any special characters, `;` or `=` for example?

Sorry for my late reply.

I recreated the "hashview" MySQL-user and set the password:
`DoNotUseThisPassword123!`
just to try this with another password, my earlier password was a 16-char autogenerated password which included special chars such as `@!€`.

However now I get:
```
Bulding Database
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/mysql/connector/connection_cext.py", line 288, in _open_connection
    self._cmysql.connect(**cnx_kwargs)
_mysql_connector.MySQLInterfaceError: Access denied for user 'hashview'@'localhost' (using password: YES)
```
but if I try the exact same (I've copied - pasted the password) to login to MySQL;
```
ubuntu@DESKTOP-A0OHB3G:~/git/hashview$ sudo mysql -u hashview -p
Enter password: <here I enter:  DoNotUseThisPassword123!>
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 23
Server version: 8.0.32-0ubuntu0.22.04.2 (Ubuntu)

Copyright (c) 2000, 2023, Oracle and/or its affiliates.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql>
```

Any ideas?

**Comment by i128** [comment]
Yeah chances are its an issue with the character set used when encoding the password. 
Best bet would be to try and use a password that uses a-zA-Z0-9 and !@#$%^&*().
