### ISSUE TITLE
mac os receive error when run ./hashview.py

### ISSUE THREAD

**Issue by pullghjunkkk** [hashview/hashview#116]
chikkachun@chikdeMBP ~ % sudo apt-get install python3 python3-pip python3-flask

git clone https://github.com/hashview/hashview/

cd hashview

pip3 install -r requirements.txt

./setup.py

./hashview.py
Password:
sudo: apt-get: command not found
fatal: destination path 'hashview' already exists and is not an empty directory.
Requirement already satisfied: flask in /usr/local/lib/python3.11/site-packages (from -r requirements.txt (line 1)) (1.1.1)
Collecting flask-wtf (from -r requirements.txt (line 2))
  Using cached Flask_WTF-1.1.1-py3-none-any.whl (12 kB)
Collecting email_validator (from -r requirements.txt (line 3))
  Downloading email_validator-2.0.0.post2-py3-none-any.whl (31 kB)
Requirement already satisfied: flask-sqlalchemy in /usr/local/lib/python3.11/site-packages (from -r requirements.txt (line 4)) (2.4.1)
Collecting mysql-connector-python (from -r requirements.txt (line 5))
  Obtaining dependency information for mysql-connector-python from https://files.pythonhosted.org/packages/b8/b2/28df4c7f5d25224352eb2c54a1eb7c75ddb5d146c27bf40c485e970119db/mysql_connector_python-8.1.0-cp311-cp311-macosx_12_0_x86_64.whl.metadata
  Downloading mysql_connector_python-8.1.0-cp311-cp311-macosx_12_0_x86_64.whl.metadata (2.0 kB)
Collecting bcrypt-flask (from -r requirements.txt (line 6))
  Downloading Bcrypt_Flask-1.0.2-py3-none-any.whl (6.6 kB)
Requirement already satisfied: flask-login in /usr/local/lib/python3.11/site-packages (from -r requirements.txt (line 7)) (0.5.0)
Collecting flask-mail (from -r requirements.txt (line 8))
  Downloading Flask-Mail-0.9.1.tar.gz (45 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.7/45.7 kB 1.6 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting flask-migrate (from -r requirements.txt (line 9))
  Using cached Flask_Migrate-4.0.4-py3-none-any.whl (20 kB)
Collecting flask-script (from -r requirements.txt (line 10))
  Downloading Flask-Script-2.0.6.tar.gz (43 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.1/43.1 kB 1.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting flask-apscheduler (from -r requirements.txt (line 11))
  Downloading Flask-APScheduler-1.12.4.tar.gz (12 kB)
  Preparing metadata (setup.py) ... done
Collecting WTForms-SQLAlchemy (from -r requirements.txt (line 12))
  Downloading WTForms_SQLAlchemy-0.3-py3-none-any.whl (8.8 kB)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/site-packages (from -r requirements.txt (line 13)) (23.1)
Collecting authlib (from -r requirements.txt (line 14))
  Obtaining dependency information for authlib from https://files.pythonhosted.org/packages/81/6e/f4522542322c7f53783da5f65464a7dee137c687111624d2ac733e2a1b98/Authlib-1.2.1-py2.py3-none-any.whl.metadata
  Downloading Authlib-1.2.1-py2.py3-none-any.whl.metadata (3.8 kB)
Requirement already satisfied: requests in /usr/local/lib/python3.11/site-packages (from -r requirements.txt (line 15)) (2.23.0)
Requirement already satisfied: Werkzeug>=0.15 in /usr/local/lib/python3.11/site-packages (from flask->-r requirements.txt (line 1)) (2.3.6)
Requirement already satisfied: Jinja2>=2.10.1 in /usr/local/lib/python3.11/site-packages (from flask->-r requirements.txt (line 1)) (3.1.2)
Requirement already satisfied: itsdangerous>=0.24 in /usr/local/lib/python3.11/site-packages (from flask->-r requirements.txt (line 1)) (2.1.2)
Requirement already satisfied: click>=5.1 in /Users/chikkachun/Library/Python/3.11/lib/python/site-packages (from flask->-r requirements.txt (line 1)) (8.0.4)
Collecting WTForms (from flask-wtf->-r requirements.txt (line 2))
  Using cached WTForms-3.0.1-py3-none-any.whl (136 kB)
Requirement already satisfied: dnspython>=2.0.0 in /usr/local/lib/python3.11/site-packages (from email_validator->-r requirements.txt (line 3)) (2.4.2)
Requirement already satisfied: idna>=2.0.0 in /usr/local/lib/python3.11/site-packages (from email_validator->-r requirements.txt (line 3)) (2.10)
Requirement already satisfied: SQLAlchemy>=0.8.0 in /usr/local/lib/python3.11/site-packages (from flask-sqlalchemy->-r requirements.txt (line 4)) (2.0.19)
Collecting protobuf<=4.21.12,>=4.21.1 (from mysql-connector-python->-r requirements.txt (line 5))
  Downloading protobuf-4.21.12-cp37-abi3-macosx_10_9_universal2.whl (486 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 486.2/486.2 kB 7.5 MB/s eta 0:00:00
Requirement already satisfied: bcrypt>=3.1.1 in /usr/local/lib/python3.11/site-packages (from bcrypt-flask->-r requirements.txt (line 6)) (3.1.7)
Collecting blinker (from flask-mail->-r requirements.txt (line 8))
  Downloading blinker-1.6.2-py3-none-any.whl (13 kB)
Collecting alembic>=1.9.0 (from flask-migrate->-r requirements.txt (line 9))
  Obtaining dependency information for alembic>=1.9.0 from https://files.pythonhosted.org/packages/ab/7d/b572fc6a51bc430b1fa0ef59591db32b14105093324d472eed8ea296d2df/alembic-1.11.3-py3-none-any.whl.metadata
  Using cached alembic-1.11.3-py3-none-any.whl.metadata (7.2 kB)
Collecting apscheduler<4.0.0,>=3.2.0 (from flask-apscheduler->-r requirements.txt (line 11))
  Obtaining dependency information for apscheduler<4.0.0,>=3.2.0 from https://files.pythonhosted.org/packages/13/b5/7af0cb920a476dccd612fbc9a21a3745fb29b1fcd74636078db8f7ba294c/APScheduler-3.10.4-py3-none-any.whl.metadata
  Downloading APScheduler-3.10.4-py3-none-any.whl.metadata (5.7 kB)
Requirement already satisfied: python-dateutil>=2.4.2 in /usr/local/lib/python3.11/site-packages (from flask-apscheduler->-r requirements.txt (line 11)) (2.8.2)
Requirement already satisfied: cryptography>=3.2 in /usr/local/lib/python3.11/site-packages (from authlib->-r requirements.txt (line 14)) (3.2)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.11/site-packages (from requests->-r requirements.txt (line 15)) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.11/site-packages (from requests->-r requirements.txt (line 15)) (1.25.11)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/site-packages (from requests->-r requirements.txt (line 15)) (2023.7.22)
Collecting Mako (from alembic>=1.9.0->flask-migrate->-r requirements.txt (line 9))
  Using cached Mako-1.2.4-py3-none-any.whl (78 kB)
Requirement already satisfied: typing-extensions>=4 in /usr/local/lib/python3.11/site-packages (from alembic>=1.9.0->flask-migrate->-r requirements.txt (line 9)) (4.7.1)
Requirement already satisfied: six>=1.4.0 in /usr/local/lib/python3.11/site-packages (from apscheduler<4.0.0,>=3.2.0->flask-apscheduler->-r requirements.txt (line 11)) (1.16.0)
Requirement already satisfied: pytz in /usr/local/lib/python3.11/site-packages (from apscheduler<4.0.0,>=3.2.0->flask-apscheduler->-r requirements.txt (line 11)) (2023.3)
Collecting tzlocal!=3.*,>=2.0 (from apscheduler<4.0.0,>=3.2.0->flask-apscheduler->-r requirements.txt (line 11))
  Obtaining dependency information for tzlocal!=3.*,>=2.0 from https://files.pythonhosted.org/packages/84/d2/730a87f0dbf184760394a85088d0d2366a5a8a32bc32ffd869a83f1de854/tzlocal-5.0.1-py3-none-any.whl.metadata
  Downloading tzlocal-5.0.1-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: cffi>=1.1 in /usr/local/lib/python3.11/site-packages (from bcrypt>=3.1.1->bcrypt-flask->-r requirements.txt (line 6)) (1.15.1)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/site-packages (from Jinja2>=2.10.1->flask->-r requirements.txt (line 1)) (2.1.3)
Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.11/site-packages (from SQLAlchemy>=0.8.0->flask-sqlalchemy->-r requirements.txt (line 4)) (2.0.2)
Requirement already satisfied: pycparser in /usr/local/lib/python3.11/site-packages (from cffi>=1.1->bcrypt>=3.1.1->bcrypt-flask->-r requirements.txt (line 6)) (2.21)
Downloading mysql_connector_python-8.1.0-cp311-cp311-macosx_12_0_x86_64.whl (10.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.0/10.0 MB 28.1 MB/s eta 0:00:00
Downloading Authlib-1.2.1-py2.py3-none-any.whl (215 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 215.3/215.3 kB 8.5 MB/s eta 0:00:00
Using cached alembic-1.11.3-py3-none-any.whl (225 kB)
Downloading APScheduler-3.10.4-py3-none-any.whl (59 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 59.3/59.3 kB 2.2 MB/s eta 0:00:00
Downloading tzlocal-5.0.1-py3-none-any.whl (20 kB)
Building wheels for collected packages: flask-mail, flask-script, flask-apscheduler
  Building wheel for flask-mail (setup.py) ... done
  Created wheel for flask-mail: filename=Flask_Mail-0.9.1-py3-none-any.whl size=7579 sha256=a916b20197a28384892e84f471bea66995b3fc5cebd803048fc3c2d767a85845
  Stored in directory: /Users/chikkachun/Library/Caches/pip/wheels/f6/38/ab/b955b60e85ca451344be85d42bd267ef32311bd61cb21e5a1c
  Building wheel for flask-script (setup.py) ... done
  Created wheel for flask-script: filename=Flask_Script-2.0.6-py3-none-any.whl size=14026 sha256=1d09645f44f58de35d2991991dc51a9c2409c003a79e57de993913568fdafa6b
  Stored in directory: /Users/chikkachun/Library/Caches/pip/wheels/a5/ce/0a/be0f1a9d96ecd772107fb97b1f69521a0196b7c70ff66b64b7
  Building wheel for flask-apscheduler (setup.py) ... done
  Created wheel for flask-apscheduler: filename=Flask_APScheduler-1.12.4-py3-none-any.whl size=15723 sha256=f21fe2a5de04d8ed305aadf89eab64fe1675dc6b9b91cf8dd639ea9688d047bd
  Stored in directory: /Users/chikkachun/Library/Caches/pip/wheels/05/cd/97/f0116ac3932bccf7c5e21b3fadbbaa25c39fb6dd012bbf3d54
Successfully built flask-mail flask-script flask-apscheduler
Installing collected packages: WTForms, tzlocal, protobuf, Mako, email_validator, blinker, WTForms-SQLAlchemy, mysql-connector-python, apscheduler, alembic, flask-wtf, flask-script, flask-mail, flask-apscheduler, bcrypt-flask, authlib, flask-migrate
  Attempting uninstall: protobuf
    Found existing installation: protobuf 4.23.4
    Uninstalling protobuf-4.23.4:
      Successfully uninstalled protobuf-4.23.4
Successfully installed Mako-1.2.4 WTForms-3.0.1 WTForms-SQLAlchemy-0.3 alembic-1.11.3 apscheduler-3.10.4 authlib-1.2.1 bcrypt-flask-1.0.2 blinker-1.6.2 email_validator-2.0.0.post2 flask-apscheduler-1.12.4 flask-mail-0.9.1 flask-migrate-4.0.4 flask-script-2.0.6 flask-wtf-1.1.1 mysql-connector-python-8.1.0 protobuf-4.21.12 tzlocal-5.0.1
Are you installing Hashview for the first time, or upgrading from an older instance?
Upgrade: 1
Fresh Install: 2
Enter choice: 
Invalid select, enter either 1 or 2.
Enter choice: 
Invalid select, enter either 1 or 2.
Enter choice: 1
See MIGRATION.md
Traceback (most recent call last):
  File "/Users/chikkachun/hashview/./hashview.py", line 12, in <module>
    from hashview import create_app
  File "/Users/chikkachun/hashview/hashview/__init__.py", line 1, in <module>
    from flask import Flask
ModuleNotFoundError: No module named 'flask'
chikkachun@chikdeMBP hashview % ./setup.py

./hashview.py
Are you installing Hashview for the first time, or upgrading from an older instance?
Upgrade: 1
Fresh Install: 2
Enter choice: 2

Collecting Hashview Database Configuration Information
Enter the IP or hostname of the server running mysql. i.e. 127.0.0.1 or localhost: 127.1.0.1
Enter the user account hashview should use to connect to the mysql instance: DoNotUseThisPassword123!
Enter the password for DoNotUseThisPassword123!: 

Collecting Hashview SMTP Configuration Information
Enter the IP or hostname of the SMTP server: poil
Enter the email address Hashview should send emails from: chikkachunckc@gmail.com
Enter username used to authenticate to the SMTP server [Enter for none]: 
Enter the password used to authenticate to the SMTP server [Enter for none]: 
Does the SMTP server use TLS? [y/N]: y
Writing hashview config at: hashview/config.conf
Bulding Database
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/bin/flask", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/flask/cli.py", line 994, in main
    cli.main(args=sys.argv[1:])
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/flask/cli.py", line 600, in main
    return super().main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1653, in invoke
    cmd_name, cmd, args = self.resolve_command(ctx, args)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1700, in resolve_command
    cmd = self.get_command(ctx, cmd_name)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/flask/cli.py", line 556, in get_command
    return info.load_app().cli.get_command(ctx, name)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/flask/cli.py", line 406, in load_app
    app = locate_app(self, import_name, name)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/flask/cli.py", line 276, in locate_app
    return find_best_app(script_info, module)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/flask/cli.py", line 68, in find_best_app
    app = call_factory(script_info, app_factory)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/flask/cli.py", line 123, in call_factory
    return app_factory(*args, **kwargs)
  File "/Users/chikkachun/hashview/hashview/__init__.py", line 19, in create_app
    from hashview.models import db
  File "/Users/chikkachun/hashview/hashview/models.py", line 8, in <module>
    from authlib import jose
ModuleNotFoundError: No module named 'authlib'
Generating SSL Certificates
..+.......+...+......+...+..+..........+...+++++++++++++++++++++++++++++++++++++++++++++*.....+....+.....+....+..............+..........+..+.+........+............+.......+..+...+..........+......+...........+++++++++++++++++++++++++++++++++++++++++++++*.........+......+...+..+...+................+.....+.+.....+............+.+..+.......+......+......+..............................+......+............+.................+.+...+..............+...............+..........+.....+...+...+.+...............+.....+......+...+....+...+..+..........+++++
.+....+...+..+++++++++++++++++++++++++++++++++++++++++++++*.........+.....+.+..+...+.+........+...+.............+.....+.+.....+...+............+.........+......+.+...+..+...+.......+.....+.......+..+.............+......+..+...+.+........+......+......+.+.....+....+...+...+..+......+.+......+.....+.......+..+.+.........+++++++++++++++++++++++++++++++++++++++++++++*.+......+...+..+...+...............+.+.....+......+....+.....................+........................+...........+.+..+.+..+....+++++
-----
You are about to be asked to enter information that will be incorporated
into your certificate request.
What you are about to enter is what is called a Distinguished Name or a DN.
There are quite a few fields but you can leave some blank
For some fields there will be a default value,
If you enter '.', the field will be left blank.
-----
Country Name (2 letter code) [AU]:HK
State or Province Name (full name) [Some-State]:hong kong
Locality Name (eg, city) []:hong kong
Organization Name (eg, company) [Internet Widgits Pty Ltd]:poskll
Organizational Unit Name (eg, section) []:osp
Common Name (e.g. server FQDN or YOUR name) []:chik
Email Address []:chikkachunckc@gmail.com
You can now start your instance of hashview by running the following command: ./hashview.py
Done.
Traceback (most recent call last):
  File "/Users/chikkachun/hashview/./hashview.py", line 12, in <module>
    from hashview import create_app
  File "/Users/chikkachun/hashview/hashview/__init__.py", line 1, in <module>
    from flask import Flask
ModuleNotFoundError: No module named 'flask'
chikkachun@chikdeMBP hashview % ./hashview.py
Traceback (most recent call last):
  File "/Users/chikkachun/hashview/./hashview.py", line 12, in <module>
    from hashview import create_app
  File "/Users/chikkachun/hashview/hashview/__init__.py", line 1, in <module>
    from flask import Flask
ModuleNotFoundError: No module named 'flask'
chikkachun@chikdeMBP hashview % pip3 install -r requirements.txt
./setup.py
./hashview.py
Requirement already satisfied: flask in /usr/local/lib/python3.11/site-packages (from -r requirements.txt (line 1)) (1.1.1)
Requirement already satisfied: flask-wtf in /usr/local/lib/python3.11/site-packages (from -r requirements.txt (line 2)) (1.1.1)
Requirement already satisfied: email_validator in /usr/local/lib/python3.11/site-packages (from -r requirements.txt (line 3)) (2.0.0.post2)
Requirement already satisfied: flask-sqlalchemy in /usr/local/lib/python3.11/site-packages (from -r requirements.txt (line 4)) (2.4.1)
Requirement already satisfied: mysql-connector-python in /usr/local/lib/python3.11/site-packages (from -r requirements.txt (line 5)) (8.1.0)
Requirement already satisfied: bcrypt-flask in /usr/local/lib/python3.11/site-packages (from -r requirements.txt (line 6)) (1.0.2)
Requirement already satisfied: flask-login in /usr/local/lib/python3.11/site-packages (from -r requirements.txt (line 7)) (0.5.0)
Requirement already satisfied: flask-mail in /usr/local/lib/python3.11/site-packages (from -r requirements.txt (line 8)) (0.9.1)
Requirement already satisfied: flask-migrate in /usr/local/lib/python3.11/site-packages (from -r requirements.txt (line 9)) (4.0.4)
Requirement already satisfied: flask-script in /usr/local/lib/python3.11/site-packages (from -r requirements.txt (line 10)) (2.0.6)
Requirement already satisfied: flask-apscheduler in /usr/local/lib/python3.11/site-packages (from -r requirements.txt (line 11)) (1.12.4)
Requirement already satisfied: WTForms-SQLAlchemy in /usr/local/lib/python3.11/site-packages (from -r requirements.txt (line 12)) (0.3)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/site-packages (from -r requirements.txt (line 13)) (23.1)
Requirement already satisfied: authlib in /usr/local/lib/python3.11/site-packages (from -r requirements.txt (line 14)) (1.2.1)
Requirement already satisfied: requests in /usr/local/lib/python3.11/site-packages (from -r requirements.txt (line 15)) (2.23.0)
Requirement already satisfied: Werkzeug>=0.15 in /usr/local/lib/python3.11/site-packages (from flask->-r requirements.txt (line 1)) (2.3.6)
Requirement already satisfied: Jinja2>=2.10.1 in /usr/local/lib/python3.11/site-packages (from flask->-r requirements.txt (line 1)) (3.1.2)
Requirement already satisfied: itsdangerous>=0.24 in /usr/local/lib/python3.11/site-packages (from flask->-r requirements.txt (line 1)) (2.1.2)
Requirement already satisfied: click>=5.1 in /Users/chikkachun/Library/Python/3.11/lib/python/site-packages (from flask->-r requirements.txt (line 1)) (8.0.4)
Requirement already satisfied: WTForms in /usr/local/lib/python3.11/site-packages (from flask-wtf->-r requirements.txt (line 2)) (3.0.1)
Requirement already satisfied: dnspython>=2.0.0 in /usr/local/lib/python3.11/site-packages (from email_validator->-r requirements.txt (line 3)) (2.4.2)
Requirement already satisfied: idna>=2.0.0 in /usr/local/lib/python3.11/site-packages (from email_validator->-r requirements.txt (line 3)) (2.10)
Requirement already satisfied: SQLAlchemy>=0.8.0 in /usr/local/lib/python3.11/site-packages (from flask-sqlalchemy->-r requirements.txt (line 4)) (2.0.19)
Requirement already satisfied: protobuf<=4.21.12,>=4.21.1 in /usr/local/lib/python3.11/site-packages (from mysql-connector-python->-r requirements.txt (line 5)) (4.21.12)
Requirement already satisfied: bcrypt>=3.1.1 in /usr/local/lib/python3.11/site-packages (from bcrypt-flask->-r requirements.txt (line 6)) (3.1.7)
Requirement already satisfied: blinker in /usr/local/lib/python3.11/site-packages (from flask-mail->-r requirements.txt (line 8)) (1.6.2)
Requirement already satisfied: alembic>=1.9.0 in /usr/local/lib/python3.11/site-packages (from flask-migrate->-r requirements.txt (line 9)) (1.11.3)
Requirement already satisfied: apscheduler<4.0.0,>=3.2.0 in /usr/local/lib/python3.11/site-packages (from flask-apscheduler->-r requirements.txt (line 11)) (3.10.4)
Requirement already satisfied: python-dateutil>=2.4.2 in /usr/local/lib/python3.11/site-packages (from flask-apscheduler->-r requirements.txt (line 11)) (2.8.2)
Requirement already satisfied: cryptography>=3.2 in /usr/local/lib/python3.11/site-packages (from authlib->-r requirements.txt (line 14)) (3.2)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.11/site-packages (from requests->-r requirements.txt (line 15)) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.11/site-packages (from requests->-r requirements.txt (line 15)) (1.25.11)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/site-packages (from requests->-r requirements.txt (line 15)) (2023.7.22)
Requirement already satisfied: Mako in /usr/local/lib/python3.11/site-packages (from alembic>=1.9.0->flask-migrate->-r requirements.txt (line 9)) (1.2.4)
Requirement already satisfied: typing-extensions>=4 in /usr/local/lib/python3.11/site-packages (from alembic>=1.9.0->flask-migrate->-r requirements.txt (line 9)) (4.7.1)
Requirement already satisfied: six>=1.4.0 in /usr/local/lib/python3.11/site-packages (from apscheduler<4.0.0,>=3.2.0->flask-apscheduler->-r requirements.txt (line 11)) (1.16.0)
Requirement already satisfied: pytz in /usr/local/lib/python3.11/site-packages (from apscheduler<4.0.0,>=3.2.0->flask-apscheduler->-r requirements.txt (line 11)) (2023.3)
Requirement already satisfied: tzlocal!=3.*,>=2.0 in /usr/local/lib/python3.11/site-packages (from apscheduler<4.0.0,>=3.2.0->flask-apscheduler->-r requirements.txt (line 11)) (5.0.1)
Requirement already satisfied: cffi>=1.1 in /usr/local/lib/python3.11/site-packages (from bcrypt>=3.1.1->bcrypt-flask->-r requirements.txt (line 6)) (1.15.1)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/site-packages (from Jinja2>=2.10.1->flask->-r requirements.txt (line 1)) (2.1.3)
Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.11/site-packages (from SQLAlchemy>=0.8.0->flask-sqlalchemy->-r requirements.txt (line 4)) (2.0.2)
Requirement already satisfied: pycparser in /usr/local/lib/python3.11/site-packages (from cffi>=1.1->bcrypt>=3.1.1->bcrypt-flask->-r requirements.txt (line 6)) (2.21)
Are you installing Hashview for the first time, or upgrading from an older instance?
Upgrade: 1
Fresh Install: 2
Enter choice: 1
See MIGRATION.md
Traceback (most recent call last):
  File "/Users/chikkachun/hashview/./hashview.py", line 12, in <module>
    from hashview import create_app
  File "/Users/chikkachun/hashview/hashview/__init__.py", line 1, in <module>
    from flask import Flask
ModuleNotFoundError: No module named 'flask'
chikkachun@chikdeMBP hashview %

**Comment by i128** [comment]
Running the server on mac has not been tested. But based on the information provided above it looks like the instance of python you're using does not have the flask module installed. I see the copied command to sudo install python-flask, did that come back with no available module?

**Comment by bandrel** [comment]
Closing as a setup/environment thread rather than a code defect — the transcript shows three unrelated local issues rather than a Hashview bug: `sudo: apt-get: command not found` (macOS has no apt), `destination path 'hashview' already exists` from a previous clone, and the final `ModuleNotFoundError: No module named 'flask'` from running `./hashview.py` against a Python that did not have the requirements installed (the pip output shows them landing in `/usr/local/lib/python3.11/site-packages` while the run used a different interpreter).

If you still want to run it on macOS, the supported paths today are `docker compose up` or a virtualenv (`python3 -m venv .venv && .venv/bin/pip install -r requirements.txt && .venv/bin/python hashview.py`). Happy to reopen if you hit an actual application error rather than a dependency-resolution one.
