### ISSUE TITLE
Getting errors when running hashview-agent.py

### ISSUE THREAD

**Issue by nmen** [hashview/hashview#117]
I'm getting this error, any ideas?

python3 ./hashview-agent.py
Traceback (most recent call last):
  File "./hashview-agent.py", line 384, in <module>
    response = send_heartbeat(agent_status, '')
  File "./hashview-agent.py", line 71, in send_heartbeat
    return api.heartbeat(agent_status, hc_status)
  File "/opt/hashview-agent/agent/api/api.py", line 12, in heartbeat
    response = http.post('/v1/agents/heartbeat', json.loads(json.dumps(message)))
  File "/opt/hashview-agent/agent/http/http.py", line 54, in post
    version = hashview.__version__
NameError: name 'hashview' is not defined

**Comment by i128** [comment]
I think you need to update your agent. 
https://github.com/hashview/hashview/commit/23c2c4889f8e41f043e4f407b02b3e040d27841d

to do this, go to your hashview server->manage->agents->Download Agent for deployment and copy/extract to /opt/

**Comment by i128** [comment]
Should be fixed now in latest release
