### ISSUE TITLE
ubuntu 16.04 server can't run hashview

### ISSUE THREAD

**Issue by aclicetom** [hashview/hashview#314]
hi, Thank you very much for this app, I follow your tutorial after the success of the installation, but not the correct run, the following is the error log:
```
21:57:16 web.1               | /home/xxx/.rvm/gems/ruby-2.2.2/gems/mustermann-1.0.0/lib/mustermann/regular.rb:40:in `check_anchors': regular expression should not contain ^: "^(?!\\/(login|register|logout|v1\\/))" (Mustermann::CompileError)
21:57:16 web.1               |  from /home/xxx/.rvm/gems/ruby-2.2.2/gems/mustermann-1.0.0/lib/mustermann/regular.rb:31:in `compile'
21:57:16 web.1               |  from /home/xxx/.rvm/gems/ruby-2.2.2/gems/mustermann-1.0.0/lib/mustermann/regexp_based.rb:19:in `initialize'
21:57:16 web.1               |  from /home/xxx/.rvm/gems/ruby-2.2.2/gems/mustermann-1.0.0/lib/mustermann/regular.rb:25:in `initialize'
21:57:16 web.1               |  from /home/xxx/.rvm/gems/ruby-2.2.2/gems/mustermann-1.0.0/lib/mustermann/pattern.rb:59:in `new'
21:57:16 web.1               |  from /home/xxx/.rvm/gems/ruby-2.2.2/gems/mustermann-1.0.0/lib/mustermann/pattern.rb:59:in `block in new'
21:57:16 web.1               |  from /home/xxx/.rvm/gems/ruby-2.2.2/gems/mustermann-1.0.0/lib/mustermann/equality_map.rb:39:in `fetch'
21:57:16 web.1               |  from /home/xxx/.rvm/gems/ruby-2.2.2/gems/mustermann-1.0.0/lib/mustermann/pattern.rb:59:in `new'
21:57:16 web.1               |  from /home/xxx/.rvm/gems/ruby-2.2.2/gems/mustermann-1.0.0/lib/mustermann.rb:67:in `new'
21:57:16 web.1               |  from /home/xxx/.rvm/gems/ruby-2.2.2/gems/sinatra-2.0.0/lib/sinatra/base.rb:1638:in `compile'
21:57:16 web.1               |  from /home/xxx/.rvm/gems/ruby-2.2.2/gems/sinatra-2.0.0/lib/sinatra/base.rb:1626:in `compile!'
21:57:16 web.1               |  from /home/xxx/.rvm/gems/ruby-2.2.2/gems/sinatra-2.0.0/lib/sinatra/base.rb:1357:in `add_filter'
21:57:16 web.1               |  from /home/xxx/.rvm/gems/ruby-2.2.2/gems/sinatra-2.0.0/lib/sinatra/base.rb:1345:in `before'
21:57:16 web.1               |  from /home/xxx/.rvm/gems/ruby-2.2.2/gems/sinatra-2.0.0/lib/sinatra/base.rb:1923:in `block (2 levels) in delegate'
21:57:16 web.1               |  from ./hashview.rb:30:in `<main>'
21:57:16 web.1               | APPLICATION VERSION: 0.6.1
21:57:16 web.1               | DB:VERSION 0.6.1
```

**Comment by i128** [comment]
Can you confirm the contents of your gemfile?  It looks like you're using sinatra-2.0.0, though the gemfile says to use 1.4.7?

```
source 'https://rubygems.org'
ruby '2.2.2'

group :development do
  gem 'rubocop'
  gem 'factory_girl'
end

group :test do
  gem 'factory_girl'
  gem 'rake'
end

gem 'sinatra', '~> 1.4.7'
gem 'sinatra-flash'
gem 'haml'
gem 'data_mapper'
gem 'dm-mysql-adapter'
gem 'data_objects'
gem 'redis'
gem 'resque'
gem 'resque-scheduler'
gem 'resque-web'
gem 'json'
gem 'pony'
gem 'bcrypt'
gem 'mysql'
gem 'foreman'
gem 'rest-client'
```

**Comment by aclicetom** [comment]
Thank you , my GemFile:
```
source 'https://rubygems.org'
ruby '2.2.2'

group :development do
  gem 'rubocop'
  gem 'factory_girl'
end

group :test do
  gem 'factory_girl'
  gem 'rake'
end

gem 'sinatra'
gem 'sinatra-flash'
gem 'haml'
gem 'data_mapper'
gem 'dm-mysql-adapter'
gem 'data_objects'
gem 'redis'
gem 'resque'
gem 'resque-scheduler'
gem 'resque-web'
gem 'json'
gem 'pony'
gem 'bcrypt'
gem 'mysql'
gem 'foreman'
gem 'rest-client'
```

**Comment by i128** [comment]
yup, you need to use version 1.4.7 of sinatra not 2.0
