### ISSUE TITLE
"remove from queue" after completion

### ISSUE THREAD

**Issue by GofX67** [hashview/hashview#464]
After the password was found, the server is getting an error 500 and the job will not stop. Everything else works fine!

(this is a "special" build: Debian 8 Jessie with backports of openssl 1.0.2, logger 1.3.0 and about 80-90 manual installed ruby gems)

Here's the interesting part of the console log:

13:17:59 mgmt-worker.1       | The client method is deprecated as of redis-rb 4.0.0, please use the new _clientmethod instead. Support for the old method will be removed in redis-namespace 2.0.
13:17:59 hashcat-worker.1    | Session..........: l8ed
13:17:59 background-worker.1 | resque-scheduler: [INFO] 2019-01-08T13:17:52+01:00: queueing RuleImporter (do_rulelist_importer)
13:17:59 web.1               | 127.0.0.1 - - [08/Jan/2019:13:17:47 +0100] "POST /v1/agents/f2fff095-4748-47da-bc9c-1a67a151be1b/heartbeat HTTP/1.1" 200 42 0.0060
13:17:59 mgmt-worker.1       | The client method is deprecated as of redis-rb 4.0.0, please use the new _clientmethod instead. Support for the old method will be removed in redis-namespace 2.0.
13:17:59 hashcat-worker.1    | Status...........: Cracked
13:17:59 web.1               | 127.0.0.1 - - [08/Jan/2019:13:17:47 CET] "POST /v1/agents/f2fff095-4748-47da-bc9c-1a67a151be1b/heartbeat HTTP/1.1" 200 42
13:17:59 mgmt-worker.1       | The client method is deprecated as of redis-rb 4.0.0, please use the new _clientmethod instead. Support for the old method will be removed in redis-namespace 2.0.
13:17:59 hashcat-worker.1    | Hash.Type........: sha512crypt $6$, SHA512 (Unix)
13:17:59 web.1               | - -> /v1/agents/f2fff095-4748-47da-bc9c-1a67a151be1b/heartbeat
13:17:59 mgmt-worker.1       | The client method is deprecated as of redis-rb 4.0.0, please use the new _clientmethod instead. Support for the old method will be removed in redis-namespace 2.0.
13:17:59 hashcat-worker.1    | Hash.Target......: $6$PyeKDy4i$BXPFm23kfGFB9gwT4wnNfzRYs7LJL68aYKhyTk7....RETL.
13:17:59 web.1               | 127.0.0.1 - - [08/Jan/2019:13:17:51 +0100] "POST /v1/agents/f2fff095-4748-47da-bc9c-1a67a151be1b/heartbeat HTTP/1.1" 200 42 0.0061
13:17:59 hashcat-worker.1    | Time.Started.....: Tue Jan  8 13:13:58 2019 (4 mins, 1 sec)
13:17:59 web.1               | 127.0.0.1 - - [08/Jan/2019:13:17:51 CET] "POST /v1/agents/f2fff095-4748-47da-bc9c-1a67a151be1b/heartbeat HTTP/1.1" 200 42
13:17:59 hashcat-worker.1    | Time.Estimated...: Tue Jan  8 13:17:59 2019 (0 secs; Runtime limited: 23 hours, 55 mins)
13:17:59 web.1               | - -> /v1/agents/f2fff095-4748-47da-bc9c-1a67a151be1b/heartbeat
13:17:59 hashcat-worker.1    | Guess.Mask.......: ?1?2?2?2?2 [5]
13:17:59 web.1               | 127.0.0.1 - - [08/Jan/2019:13:17:55 +0100] "POST /v1/agents/f2fff095-4748-47da-bc9c-1a67a151be1b/heartbeat HTTP/1.1" 200 42 0.0062
13:17:59 hashcat-worker.1    | Guess.Charset....: -1 ?l?d?u, -2 ?l?d, -3 ?l?d*!$@_, -4 Undefined 
13:17:59 web.1               | 127.0.0.1 - - [08/Jan/2019:13:17:55 CET] "POST /v1/agents/f2fff095-4748-47da-bc9c-1a67a151be1b/heartbeat HTTP/1.1" 200 42
13:17:59 hashcat-worker.1    | Guess.Queue......: 5/15 (33.33%)
13:17:59 web.1               | - -> /v1/agents/f2fff095-4748-47da-bc9c-1a67a151be1b/heartbeat
13:17:59 hashcat-worker.1    | Speed.Dev.#1.....:    69759 H/s (74.89ms) @ Accel:512 Loops:128 Thr:32 Vec:1
13:17:59 hashcat-worker.1    | Recovered........: 1/1 (100.00%) Digests, 1/1 (100.00%) Salts
13:17:59 hashcat-worker.1    | Progress.........: 16826368/104136192 (16.16%)
13:17:59 hashcat-worker.1    | Rejected.........: 0/16826368 (0.00%)
13:17:59 hashcat-worker.1    | Restore.Point....: 212992/1679616 (12.68%)
13:17:59 hashcat-worker.1    | Candidates.#1....: g4sro -> ggkku
13:17:59 hashcat-worker.1    | HWMon.Dev.#1.....: Temp: 66c Fan: 52% Util: 95% Core:1341MHz Mem:3004MHz Bus:16
13:17:59 hashcat-worker.1    | 
13:17:59 web.1               | 127.0.0.1 - - [08/Jan/2019:13:17:59 +0100] "POST /v1/agents/f2fff095-4748-47da-bc9c-1a67a151be1b/heartbeat HTTP/1.1" 200 42 0.0058
13:17:59 web.1               | 127.0.0.1 - - [08/Jan/2019:13:17:59 CET] "POST /v1/agents/f2fff095-4748-47da-bc9c-1a67a151be1b/heartbeat HTTP/1.1" 200 42
13:17:59 web.1               | - -> /v1/agents/f2fff095-4748-47da-bc9c-1a67a151be1b/heartbeat
13:18:00 hashcat-worker.1    | Started: Tue Jan  8 13:12:55 2019
Stopped: Tue Jan  8 13:18:00 2019
13:18:02 web.1               | 127.0.0.1 - - [08/Jan/2019:13:18:02 +0100] "GET /home HTTP/1.1" 200 5844 0.0092
13:18:02 web.1               | 127.0.0.1 - - [08/Jan/2019:13:18:02 CET] "GET /home HTTP/1.1" 200 5844
13:18:02 web.1               | - -> /home
13:18:02 web.1               | 127.0.0.1 - - [08/Jan/2019:13:18:02 +0100] "GET /js/jquery-2.1.3.min.js HTTP/1.1" 304 - 0.0006
13:18:02 web.1               | 127.0.0.1 - - [08/Jan/2019:13:18:02 CET] "GET /js/jquery-2.1.3.min.js HTTP/1.1" 304 0
13:18:02 web.1               | https://127.0.0.1:4567/home -> /js/jquery-2.1.3.min.js
13:18:02 web.1               | 127.0.0.1 - - [08/Jan/2019:13:18:02 +0100] "GET /css/Light.css HTTP/1.1" 304 - 0.0005
13:18:02 web.1               | 127.0.0.1 - - [08/Jan/2019:13:18:02 CET] "GET /css/Light.css HTTP/1.1" 304 0
13:18:02 web.1               | https://127.0.0.1:4567/home -> /css/Light.css
13:18:02 web.1               | 127.0.0.1 - - [08/Jan/2019:13:18:02 +0100] "GET /js/bootstrap.js HTTP/1.1" 304 - 0.0005
13:18:02 web.1               | 127.0.0.1 - - [08/Jan/2019:13:18:02 CET] "GET /js/bootstrap.js HTTP/1.1" 304 0
13:18:02 web.1               | https://127.0.0.1:4567/home -> /js/bootstrap.js
13:18:02 web.1               | 127.0.0.1 - - [08/Jan/2019:13:18:02 +0100] "GET /js/modules.js HTTP/1.1" 304 - 0.0008
13:18:02 web.1               | 127.0.0.1 - - [08/Jan/2019:13:18:02 CET] "GET /js/modules.js HTTP/1.1" 304 0
13:18:02 web.1               | https://127.0.0.1:4567/home -> /js/modules.js
13:18:02 web.1               | 127.0.0.1 - - [08/Jan/2019:13:18:02 +0100] "GET /css/hashviewStyle.css HTTP/1.1" 304 - 0.0009
13:18:02 web.1               | 127.0.0.1 - - [08/Jan/2019:13:18:02 CET] "GET /css/hashviewStyle.css HTTP/1.1" 304 0
13:18:02 web.1               | https://127.0.0.1:4567/home -> /css/hashviewStyle.css
13:18:02 background-worker.1 | resque-scheduler: [INFO] 2019-01-08T13:18:02+01:00: queueing RuleImporter (do_rulelist_importer)
13:18:03 web.1               | 127.0.0.1 - - [08/Jan/2019:13:18:03 +0100] "POST /v1/agents/f2fff095-4748-47da-bc9c-1a67a151be1b/heartbeat HTTP/1.1" 200 42 0.0055
13:18:03 web.1               | 127.0.0.1 - - [08/Jan/2019:13:18:03 CET] "POST /v1/agents/f2fff095-4748-47da-bc9c-1a67a151be1b/heartbeat HTTP/1.1" 200 42
13:18:03 web.1               | - -> /v1/agents/f2fff095-4748-47da-bc9c-1a67a151be1b/heartbeat
13:18:04 web.1               | 127.0.0.1 - - [08/Jan/2019:13:18:04 +0100] "POST /v1/queue/6/status HTTP/1.1" 200 - 0.0039
13:18:04 web.1               | 127.0.0.1 - - [08/Jan/2019:13:18:04 CET] "POST /v1/queue/6/status HTTP/1.1" 200 0
13:18:04 web.1               | - -> /v1/queue/6/status
13:18:04 hashcat-worker.1    | "setting status to importing"
13:18:04 hashcat-worker.1    | "Uploading cracked hashes."
13:18:04 mgmt-worker.1       | The client method is deprecated as of redis-rb 4.0.0, please use the new _clientmethod instead. Support for the old method will be removed in redis-namespace 2.0.
13:18:04 web.1               | 127.0.0.1 - - [08/Jan/2019:13:18:04 +0100] "POST /v1/jobtask/6/crackfile/upload HTTP/1.1" 200 17 0.0096
13:18:04 web.1               | 127.0.0.1 - - [08/Jan/2019:13:18:04 CET] "POST /v1/jobtask/6/crackfile/upload HTTP/1.1" 200 17
13:18:04 web.1               | - -> /v1/jobtask/6/crackfile/upload
13:18:04 web.1               | 2019-01-08 13:18:04 - NoMethodError - undefined method `split' for nil:NilClass:
13:18:04 web.1               | 	/home/glenn/Schreibtisch/hashcat/hashview/helpers/email.rb:5:in `sendEmail'
13:18:04 web.1               | 	/home/glenn/Schreibtisch/hashcat/hashview/helpers/status.rb:102:in `updateJobTaskStatus'
13:18:04 web.1               | 	/home/glenn/Schreibtisch/hashcat/hashview/helpers/status.rb:55:in `updateTaskqueueStatus'
13:18:04 web.1               | 	/home/glenn/Schreibtisch/hashcat/hashview/routes/api.rb:77:in `block in <top (required)>'
13:18:04 web.1               | 	/usr/local/rvm/gems/ruby-2.4.4/gems/sinatra-2.0.4/lib/sinatra/base.rb:1635:in `call'
13:18:04 web.1               | 	/usr/local/rvm/gems/ruby-2.4.4/gems/sinatra-2.0.4/lib/sinatra/base.rb:1635:in `block in compile!'
13:18:04 web.1               | 	/usr/local/rvm/gems/ruby-2.4.4/gems/sinatra-2.0.4/lib/sinatra/base.rb:992:in `block (3 levels) in route!'
13:18:04 web.1               | 	/usr/local/rvm/gems/ruby-2.4.4/gems/sinatra-2.0.4/lib/sinatra/base.rb:1011:in `route_eval'
13:18:04 web.1               | 	/usr/local/rvm/gems/ruby-2.4.4/gems/sinatra-2.0.4/lib/sinatra/base.rb:992:in `block (2 levels) in route!'
13:18:04 web.1               | 	/usr/local/rvm/gems/ruby-2.4.4/gems/sinatra-2.0.4/lib/sinatra/base.rb:1040:in `block in process_route'
13:18:04 web.1               | 	/usr/local/rvm/gems/ruby-2.4.4/gems/sinatra-2.0.4/lib/sinatra/base.rb:1038:in `catch'
13:18:04 web.1               | 	/usr/local/rvm/gems/ruby-2.4.4/gems/sinatra-2.0.4/lib/sinatra/base.rb:1038:in `process_route'
13:18:04 web.1               | 	/usr/local/rvm/gems/ruby-2.4.4/gems/sinatra-2.0.4/lib/sinatra/base.rb:990:in `block in route!'
13:18:04 web.1               | 	/usr/local/rvm/gems/ruby-2.4.4/gems/sinatra-2.0.4/lib/sinatra/base.rb:989:in `each'
13:18:04 web.1               | 	/usr/local/rvm/gems/ruby-2.4.4/gems/sinatra-2.0.4/lib/sinatra/base.rb:989:in `route!'
13:18:04 web.1               | 	/usr/local/rvm/gems/ruby-2.4.4/gems/sinatra-2.0.4/lib/sinatra/base.rb:1097:in `block in dispatch!'
13:18:04 web.1               | 	/usr/local/rvm/gems/ruby-2.4.4/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `block in invoke'
13:18:04 web.1               | 	/usr/local/rvm/gems/ruby-2.4.4/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `catch'
13:18:04 web.1               | 	/usr/local/rvm/gems/ruby-2.4.4/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `invoke'
13:18:04 web.1               | 	/usr/local/rvm/gems/ruby-2.4.4/gems/sinatra-2.0.4/lib/sinatra/base.rb:1094:in `dispatch!'
13:18:04 web.1               | 	/usr/local/rvm/gems/ruby-2.4.4/gems/sinatra-2.0.4/lib/sinatra/base.rb:924:in `block in call!'
13:18:04 web.1               | 	/usr/local/rvm/gems/ruby-2.4.4/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `block in invoke'
13:18:04 web.1               | 	/usr/local/rvm/gems/ruby-2.4.4/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `catch'
13:18:04 web.1               | 	/usr/local/rvm/gems/ruby-2.4.4/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `invoke'
13:18:04 web.1               | 	/usr/local/rvm/gems/ruby-2.4.4/gems/sinatra-2.0.4/lib/sinatra/base.rb:924:in `call!'
13:18:04 web.1               | 	/usr/local/rvm/gems/ruby-2.4.4/gems/sinatra-2.0.4/lib/sinatra/base.rb:913:in `call'
13:18:04 web.1               | 	/usr/local/rvm/gems/ruby-2.4.4/gems/rack-protection-2.0.4/lib/rack/protection/escaped_params.rb:53:in `call'
13:18:04 web.1               | 	/usr/local/rvm/gems/ruby-2.4.4/gems/rack-protection-2.0.4/lib/rack/protection/xss_header.rb:18:in `call'
13:18:04 web.1               | 	/usr/local/rvm/gems/ruby-2.4.4/gems/rack-protection-2.0.4/lib/rack/protection/base.rb:50:in `call'
13:18:04 web.1               | 	/usr/local/rvm/gems/ruby-2.4.4/gems/rack-protection-2.0.4/lib/rack/protection/base.rb:50:in `call'
13:18:04 web.1               | 	/usr/local/rvm/gems/ruby-2.4.4/gems/rack-protection-2.0.4/lib/rack/protection/path_traversal.rb:16:in `call'
13:18:04 web.1               | 	/usr/local/rvm/gems/ruby-2.4.4/gems/rack-protection-2.0.4/lib/rack/protection/json_csrf.rb:26:in `call'
13:18:04 web.1               | 	/usr/local/rvm/gems/ruby-2.4.4/gems/rack-protection-2.0.4/lib/rack/protection/base.rb:50:in `call'
13:18:04 web.1               | 	/usr/local/rvm/gems/ruby-2.4.4/gems/rack-protection-2.0.4/lib/rack/protection/base.rb:50:in `call'
13:18:04 web.1               | 	/usr/local/rvm/gems/ruby-2.4.4/gems/rack-protection-2.0.4/lib/rack/protection/frame_options.rb:31:in `call'
13:18:04 web.1               | 	/usr/local/rvm/gems/ruby-2.4.4/gems/rack-2.0.6/lib/rack/session/abstract/id.rb:232:in `context'
13:18:04 web.1               | 	/usr/local/rvm/gems/ruby-2.4.4/gems/rack-2.0.6/lib/rack/session/abstract/id.rb:226:in `call'
13:18:04 web.1               | 	/usr/local/rvm/gems/ruby-2.4.4/gems/rack-2.0.6/lib/rack/logger.rb:15:in `call'
13:18:04 web.1               | 	/usr/local/rvm/gems/ruby-2.4.4/gems/rack-2.0.6/lib/rack/common_logger.rb:33:in `call'
13:18:04 web.1               | 	/usr/local/rvm/gems/ruby-2.4.4/gems/sinatra-2.0.4/lib/sinatra/base.rb:231:in `call'
13:18:04 web.1               | 	/usr/local/rvm/gems/ruby-2.4.4/gems/sinatra-2.0.4/lib/sinatra/base.rb:224:in `call'
13:18:04 web.1               | 	/usr/local/rvm/gems/ruby-2.4.4/gems/rack-2.0.6/lib/rack/head.rb:12:in `call'
13:18:04 web.1               | 	/usr/local/rvm/gems/ruby-2.4.4/gems/rack-2.0.6/lib/rack/method_override.rb:22:in `call'
13:18:04 web.1               | 	/usr/local/rvm/gems/ruby-2.4.4/gems/sinatra-2.0.4/lib/sinatra/base.rb:194:in `call'
13:18:04 web.1               | 	/usr/local/rvm/gems/ruby-2.4.4/gems/sinatra-2.0.4/lib/sinatra/base.rb:1957:in `call'
13:18:04 web.1               | 	/usr/local/rvm/gems/ruby-2.4.4/gems/sinatra-2.0.4/lib/sinatra/base.rb:1502:in `block in call'
13:18:04 web.1               | 	/usr/local/rvm/gems/ruby-2.4.4/gems/sinatra-2.0.4/lib/sinatra/base.rb:1729:in `synchronize'
13:18:04 web.1               | 	/usr/local/rvm/gems/ruby-2.4.4/gems/sinatra-2.0.4/lib/sinatra/base.rb:1502:in `call'
13:18:04 web.1               | 	/usr/local/rvm/gems/ruby-2.4.4/gems/rack-2.0.6/lib/rack/handler/webrick.rb:86:in `service'
13:18:04 web.1               | 	/usr/local/rvm/rubies/ruby-2.4.4/lib/ruby/2.4.0/webrick/httpserver.rb:140:in `service'
13:18:04 web.1               | 	/usr/local/rvm/rubies/ruby-2.4.4/lib/ruby/2.4.0/webrick/httpserver.rb:96:in `run'
13:18:04 web.1               | 	/usr/local/rvm/rubies/ruby-2.4.4/lib/ruby/2.4.0/webrick/server.rb:308:in `block in start_thread'
13:18:04 web.1               | 127.0.0.1 - - [08/Jan/2019:13:18:04 +0100] "POST /v1/queue/6/status HTTP/1.1" 500 30 0.0127
13:18:04 web.1               | 127.0.0.1 - - [08/Jan/2019:13:18:04 CET] "POST /v1/queue/6/status HTTP/1.1" 500 30
13:18:04 web.1               | - -> /v1/queue/6/status
13:18:04 hashcat-worker.1    | 500 Internal Server Error
13:18:04 hashcat-worker.1    | "setting status to complete"

Any ideas?

**Comment by GofX67** [comment]
Found!

Everything was caused by a mail config error.
14:34:42 hashcat-worker.1    | Started: Tue Jan  8 14:29:40 2019
Stopped: Tue Jan  8 14:34:42 2019
14:34:44 web.1               | 127.0.0.1 - - [08/Jan/2019:14:34:44 +0100] "POST /v1/agents/f2fff095-4748-47da-bc9c-1a67a151be1b/heartbeat HTTP/1.1" 200 42 0.0055
14:34:44 web.1               | 127.0.0.1 - - [08/Jan/2019:14:34:44 CET] "POST /v1/agents/f2fff095-4748-47da-bc9c-1a67a151be1b/heartbeat HTTP/1.1" 200 42
14:34:44 web.1               | - -> /v1/agents/f2fff095-4748-47da-bc9c-1a67a151be1b/heartbeat
14:34:44 web.1               | 127.0.0.1 - - [08/Jan/2019:14:34:44 +0100] "POST /v1/queue/7/status HTTP/1.1" 200 - 0.0041
14:34:44 web.1               | 127.0.0.1 - - [08/Jan/2019:14:34:44 CET] "POST /v1/queue/7/status HTTP/1.1" 200 0
14:34:44 web.1               | - -> /v1/queue/7/status
14:34:44 hashcat-worker.1    | "setting status to importing"
14:34:44 hashcat-worker.1    | "Uploading cracked hashes."
14:34:44 web.1               | 127.0.0.1 - - [08/Jan/2019:14:34:44 +0100] "POST /v1/jobtask/7/crackfile/upload HTTP/1.1" 200 17 0.0083
14:34:44 web.1               | 127.0.0.1 - - [08/Jan/2019:14:34:44 CET] "POST /v1/jobtask/7/crackfile/upload HTTP/1.1" 200 17
14:34:44 web.1               | - -> /v1/jobtask/7/crackfile/upload
14:34:44 web.1               | 127.0.0.1 - - [08/Jan/2019:14:34:44 +0100] "POST /v1/queue/7/status HTTP/1.1" 200 - 0.1409
14:34:44 web.1               | 127.0.0.1 - - [08/Jan/2019:14:34:44 CET] "POST /v1/queue/7/status HTTP/1.1" 200 0
14:34:44 web.1               | - -> /v1/queue/7/status
14:34:44 hashcat-worker.1    | "setting status to complete"

Thanks!
