### ISSUE TITLE
Jobs Queued

### ISSUE THREAD

**Issue by NoobCam** [hashview/hashview#476]
Running on ```Ubuntu 18.04.2 LTS```

Had a power outage and now jobs just get queued when adding.

Hashcat runs fine from command line

The uuid and the hashcat file path are correct in the config.

Starting the hashview service i get

```
RACK_ENV=production foreman start
16:13:44 redis.1             | started with pid 10517
16:13:44 mgmt-worker.1       | started with pid 10518
16:13:44 hashcat-worker.1    | started with pid 10519
16:13:44 background-worker.1 | started with pid 10521
16:13:44 web.1               | started with pid 10523
16:13:44 redis.1             | 10517:C 01 Aug 16:13:44.279 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
16:13:44 redis.1             | 10517:C 01 Aug 16:13:44.279 # Redis version=4.0.9, bits=64, commit=00000000, modified=0, pid=10517, just started
16:13:44 redis.1             | 10517:C 01 Aug 16:13:44.279 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
16:13:44 redis.1             | 10517:M 01 Aug 16:13:44.279 * Increased maximum number of open files to 10032 (it was originally set to 1024).
16:13:44 redis.1             | 10517:M 01 Aug 16:13:44.279 # Creating Server TCP listening socket *:6379: bind: Address already in use
16:13:44 redis.1             | exited with code 1
16:13:44 system              | sending SIGTERM to all processes
16:13:44 mgmt-worker.1       | terminated by SIGTERM
16:13:44 hashcat-worker.1    | terminated by SIGTERM
16:13:44 background-worker.1 | terminated by SIGTERM
16:13:44 web.1               | terminated by SIGTERM
16:13:44                     | The client method is deprecated as of redis-rb 4.0.0, please use the new _clientmethod instead. Support for the old method will be removed in redis-namespace 2.0.
16:13:44                     | resque-scheduler: [INFO] 2019-08-01T16:13:44+00:00: Starting
16:13:44                     | resque-scheduler: [INFO] 2019-08-01T16:13:44+00:00: Loading Schedule
16:13:44                     | resque-scheduler: [INFO] 2019-08-01T16:13:44+00:00: Scheduling do_wordlist_importer 
16:13:44                     | resque-scheduler: [INFO] 2019-08-01T16:13:44+00:00: Scheduling do_rulelist_importer 
16:13:44                     | resque-scheduler: [INFO] 2019-08-01T16:13:44+00:00: Scheduling do_cleanUp 
16:13:44                     | resque-scheduler: [INFO] 2019-08-01T16:13:44+00:00: Schedules Loaded
16:13:44                     | Passing 'info' command to redis as is; administrative commands cannot be effectively namespaced and should be called on the redis connection directly; passthrough has been deprecated and will be removed in redis-namespace 2.0 (at /usr/share/rvm/gems/ruby-2.4.4/gems/resque-1.27.4/lib/resque/data_store.rb:59:in `method_missing')
16:13:44                     | Passing 'script' command to redis as is; administrative commands cannot be effectively namespaced and should be called on the redis connection directly; passthrough has been deprecated and will be removed in redis-namespace 2.0 (at /usr/share/rvm/gems/ruby-2.4.4/gems/resque-1.27.4/lib/resque/data_store.rb:59:in `method_missing')
```
if I run ``` service redis-server stop``` it seems redis automaticly restarts itself.

I did check the resque web interface and no queued jobs are listed.

I cannot physically reboot this machine as it gets stuck on boot and I am not physically at the console.

**Comment by NoobCam** [comment]
Resolved by restarting the box itself. Please close

**Comment by ccammilleri** [comment]
glad you got it resolved!
