### ISSUE TITLE
Issue installing agent

### ISSUE THREAD

**Issue by CryptoAssetRecovery** [hashview/hashview#62]
Hello all, this may be a silly question with a simple answer, however, during the installation process I have successfully installed the client but a ConnectionResetError is being thrown when I enter the path to a local hashcat install. 

The error code is as follows:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1348, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 277, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/crypto/.local/lib/python3.8/site-packages/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 719, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 400, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3/dist-packages/six.py", line 702, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1348, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 277, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./hashview-agent.py", line 384, in <module>
    response = send_heartbeat(agent_status, '')
  File "./hashview-agent.py", line 71, in send_heartbeat
    return api.heartbeat(agent_status, hc_status)
  File "/home/crypto/Downloads/hashview-agent/agent/api/api.py", line 12, in heartbeat
    response = [http.post](http://http.post/)('/v1/agents/heartbeat', json.loads(json.dumps(message)))
  File "/home/crypto/Downloads/hashview-agent/agent/http/http.py", line 70, in post
    response = [http.post](http://http.post/)(path, data=json.dumps(data), verify=False, cookies=cookie, headers=headers)
  File "/home/crypto/.local/lib/python3.8/site-packages/requests/sessions.py", line 577, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/home/crypto/.local/lib/python3.8/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/crypto/.local/lib/python3.8/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/home/crypto/.local/lib/python3.8/site-packages/requests/adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

Any stupid mistakes I could've made or proposed fixes?

**Comment by i128** [comment]
Are the agent/server both on the same network? 
What does your agent/config.conf look like?

**Comment by CryptoAssetRecovery** [comment]
Thanks for your response. 

Yes, the agent and client are on the same server actually. I'll copy the config.conf file below.

[HASHVIEW]
server = XXX.X.X.X
port = 8443
use_ssl = False

[AGENT]
name = util-server
uuid = XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX
HC_BIN_PATH = /home/util/Desktop/hashcat-6.2.4

**Comment by CryptoAssetRecovery** [comment]
Had some stupid mistakes in there but i sorted it, thank you much!

**Comment by kazuma7095** [comment]
> Had some stupid mistakes in there but i sorted it, thank you much!

What was the mistake i cant seem to find where it went wrong.
