### ISSUE TITLE
Issues running ./hashview-agent.py

### ISSUE THREAD

**Issue by nmen** [hashview/hashview#69]
Hi All,

Getting the below errors when running ./hashview-agent.py

Any ideas?

Traceback (most recent call last):
  File "./hashview-agent.py", line 385, in <module>
    response = send_heartbeat(agent_status, '')
  File "./hashview-agent.py", line 72, in send_heartbeat
    return api.heartbeat(agent_status, hc_status)
  File "/opt/hashview/install/hashview-agent/agent/api/api.py", line 12, in heartbeat
    response = http.post('/v1/agents/heartbeat', json.loads(json.dumps(message)))
  File "/opt/hashview/install/hashview-agent/agent/http/http.py", line 54, in post
    version = hashview.__version__
NameError: name 'hashview' is not defined

**Comment by i128** [comment]
What version of python are you using?
are you running the agent as root?

**Comment by i128** [comment]
no feedback closing.
