### ISSUE TITLE
Opening settings results in error.

### ISSUE THREAD

**Issue by JasY95** [hashview/hashview#95]
Clicking "settings" results in an error:

ERROR [hashview] Exception on /settings [GET]
Traceback (most recent call last):
  File "/home/jy/.local/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jy/.local/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jy/.local/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jy/.local/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/jy/.local/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/jy/hashview/hashview/settings/routes.py", line 42, in settings_list
    database_version    = db.get_engine(current_app).execute('SELECT version_num FROM alembic_version LIMIT 1;').fetchone()[0],
  File "/home/jy/.local/lib/python3.10/site-packages/flask_sqlalchemy/extension.py", line 666, in get_engine
    return self.engines[bind_key]
KeyError: <Flask 'hashview'>

**Comment by JasY95** [comment]
Thanks for the help. Unfortunately, that doesn't fix it. I'm running a 96x RTX 3090 cluster so I'm keen to get going.

**Comment by i128** [comment]
Dang, yeah i would love to see those benchmarks once things are running.
  
  Can you log into the database and report back whats populated in the following table? does it even exist?
  
  ```
mysql -u hashview -h < host where you have the sql server> -p

> use hashview;
> select * from alembic_version;
  ```

**Comment by JasY95** [comment]
mysql> select * from alembic_version;
+--------------+
| version_num  |
+--------------+
| b4a9f18259b9 |
+--------------+
1 row in set (0.00 sec)

**Comment by i128** [comment]
I may take you up on that, or at least to help quicken the trouble shooting.
The good news is that the data is there.
Im not 100% sure yet though why its have that problem. 

@Yoshi325 
Any thoughts? IIRC this was your addition.

I dont think we could just swap out the query to something like `db.session.query(...)` since its not in the model?

**Comment by i128** [comment]
Should be fixed now in latest release
